---
- name: download yq
  get_url:
    url: "https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64"
    dest: "/tmp/yq"

- name: make it executable
  become: true
  ansible.builtin.file:
    path: /tmp/yq
    mode: '0755'

- name: move to local bin
  become: true
  command: mv /tmp/yq /usr/local/bin/yq

- name: delete tmp file
  become: true
  ansible.builtin.file:
    path: /tmp/yq
    state: absent

- name: yq version
  shell: yq --version
