---
- name: download golang
  get_url:
    url: "https://go.dev/dl/go{{ golang_version }}.linux-amd64.tar.gz"
    dest: "/tmp/go{{ golang_version }}.linux-amd64.tar.gz"

- name: delete old go folder
  become: true
  ansible.builtin.file:
    path: /usr/local/go
    state: absent

# - name: unzip golang
#   become: true
#   shell: tar -C /usr/local -xzf "/tmp/go{{ golang_version }}.linux-amd64.tar.gz"

- name: Extract foo.tgz into /var/lib/foo
  become: true
  ansible.builtin.unarchive:
    src: "/tmp/go{{ golang_version }}.linux-amd64.tar.gz"
    dest: /usr/local
    remote_src: yes

- name: delete tmp zip file
  become: true
  ansible.builtin.file:
    path: "/tmp/go{{ golang_version }}.linux-amd64.tar.gz"
    state: absent

- name: add to path
  shell: echo "export PATH=$PATH:/usr/local/go/bin" >> /home/{{ user }}/.bashrc

- name: golang version
  shell: /usr/local/go/bin/go version
