---
- hosts: 127.0.0.1
  connection: local
  become: true
  vars:
    tools:
      - tree
      - curl
      - cowsay
  roles:
    - {role: tools, tag: ['dev']}
    - {role: node_agent, tag: ['dev']}
