---
- hosts: 127.0.0.1
  connection: local
  become: true
  vars:
    tools:
      - jq
      - git
      - tree
      - curl
      - cowsay
  roles:
    - {role: tools, tag: ['dev']}
    - {role: golang, tag: ['dev']}
    - {role: erlang, tag: ['dev']}
