---
- name: add repo rabbitmq-erlang
  become: true
  # command: add-apt-repository ppa:rabbitmq/rabbitmq-erlang -y
  ansible.builtin.apt_repository:
    repo: ppa:rabbitmq/rabbitmq-erlang

- name: update repo
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: Install erlang/elixir
  ansible.builtin.apt:
    pkg:
    - erlang
    - elixir
