---
# https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=22.04&target_type=deb_network
- name: download keyring
  get_url:
    url: "https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb"
    dest: "/tmp/cuda-keyring_1.1-1_all.deb"

- name: install cuda keyring
  become: true
  command: dpkg -i /tmp/cuda-keyring_1.1-1_all.deb

- name: delete cuda-keyring
  become: true
  ansible.builtin.file:
    path: "/tmp/cuda-keyring_1.1-1_all.deb"
    state: absent

- name: update repo
  become: true
  apt:
    upgrade: no
    update_cache: yes

- name: Install cuda toolkit
  ansible.builtin.apt:
    pkg:
      - cuda-toolkit-12-4
      - libcudnn8
      - nvtop
  when: package.cuda_toolkit | default(false)

- name: Install legacy cuda drivers
  ansible.builtin.apt:
    pkg:
      - cuda-drivers
  when: package.cuda_driver | default(false)

- name: Install nvidia-container-toolkit
  ansible.builtin.apt:
    pkg:
      - nvidia-container-toolkit
  when: package.nvidia_container_toolkit | default(false)
